# Generated by Django 2.0.7 on 2018-08-10 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mapsapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rms',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VersionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='rms',
            name='tags',
            field=models.ManyToManyField(to='mapsapp.Tag'),
        ),
        migrations.AddField(
            model_name='rms',
            name='versiontags',
            field=models.ManyToManyField(to='mapsapp.VersionTag'),
        ),
        migrations.AddField(
            model_name='image',
            name='rms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapsapp.Rms'),
        ),
        migrations.AddField(
            model_name='rms',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rms',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='rms',
            name='filename',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='filename',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=mapsapp.models.rms_image_path),
        ),
        migrations.AlterField(
            model_name='rms',
            name='file',
            field=models.FileField(upload_to=mapsapp.models.rms_image_path),
        ),
        migrations.AlterField(
            model_name='rms',
            name='file',
            field=models.FileField(upload_to=mapsapp.models.rms_path),
        ),
        migrations.AddField(
            model_name='rms',
            name='authors',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rms',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rms',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rms',
            name='version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('rms', models.ManyToManyField(blank=True, to='mapsapp.Rms')),
                ('authors', models.CharField(default='', max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='rms',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rms',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
