# Generated by Django 2.0.7 on 2018-08-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0002_auto_20180813_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='rms',
            name='newer_version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapsapp.Rms'),
        ),
    ]
