# Generated by Django 2.0.7 on 2018-09-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0005_collection_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rms',
            name='information',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
