# Generated by Django 2.0.7 on 2018-09-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0006_rms_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rms',
            name='information',
            field=models.TextField(blank=True, default=None),
        ),
    ]
