# Generated by Django 2.1 on 2018-09-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0008_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rms',
            name='changelog',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rms',
            name='information',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rms',
            name='newer_version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessors', to='mapsapp.Rms'),
        ),
    ]
