# Generated by Django 2.1 on 2018-10-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0009_auto_20180922_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
