# Generated by Django 2.1.2 on 2018-10-25 20:07

from django.db import migrations, models
import mapsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0010_image_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=mapsapp.models.rms_image_path),
        ),
    ]
