# Generated by Django 2.1.10 on 2019-07-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0013_auto_20181222_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='rms',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
