# Generated by Django 2.1.11 on 2019-10-02 21:48

from django.db import migrations, models
import django.db.models.deletion
import mapsapp.models
import storages.backends.azure_storage


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0014_rms_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='RmsCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapsapp.Collection')),
                ('rms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapsapp.Rms')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(storage=storages.backends.azure_storage.AzureStorage(), upload_to=mapsapp.models.rms_image_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='preview',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(), upload_to=mapsapp.models.rms_image_path),
        ),
    ]
