# Generated by Django 2.1.11 on 2019-10-02 21:48

from django.db import migrations


def create_through_relations(apps, schema_editor):
    RmsCollection = apps.get_model('mapsapp', 'RmsCollection')
    Collection = apps.get_model('mapsapp', 'Collection')
    for collection in Collection.objects.all():
        for rms in collection.rms.all():
            RmsCollection(
                rms=rms,
                collection=collection
            ).save()


class Migration(migrations.Migration):
    dependencies = [
        ('mapsapp', '0015_add_rms_collection_class'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
