# Generated by Django 2.1.11 on 2019-10-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0016_migrate_rms_collection_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='rms',
        ),
    ]
