# Generated by Django 2.1.11 on 2019-10-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0017_remove_collection_rms'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='rms',
            field=models.ManyToManyField(blank=True, through='mapsapp.RmsCollection', to='mapsapp.Rms'),
        ),
    ]
