# Generated by Django 4.0.1 on 2022-01-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0021_rms_id'),
    ]

    @staticmethod
    def calculate_id(collection_uuid, collection_model):
        uuid_str = str(collection_uuid)
        for strlen in range(6, len(uuid_str)-1):
            candidate = uuid_str[:strlen]
            if not collection_model.objects.filter(id=candidate):
                return candidate

    def calculate_defaults(apps, schema_editor):
        Collection = apps.get_model('mapsapp', 'Collection')
        for collection in Collection.objects.all().iterator():
            collection.id = Migration.calculate_id(collection.uuid, Collection)
            collection.save()

    operations = [
        migrations.AddField(
            model_name='collection',
            name='id',
            field=models.CharField(null=True, max_length=255),
        ),
        migrations.RunPython(calculate_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
